(async function(){
 'use strict';
 const base=document.querySelector('meta[name=hansgal-base]')?.content||'',de=document.documentElement.lang==='de',t=(a,b)=>de?b:a;
 if(!/\/hansgal\/26\/?$/.test(location.pathname))return;
 const article=document.querySelector('.article'),table=article?.querySelector('table');if(!table)return;
 const note=document.createElement('p');note.className='chronology-instructions';note.textContent=t('Hover over a date, or select it, to discover music from that period. Select a work to open its catalogue page. “pub.” marks a publication date where the composition date is unknown.','Zeigen Sie auf ein Datum oder wählen Sie es aus, um die Musik dieser Zeit zu entdecken. Ein Werktitel führt zum Werkverzeichnis. „pub.“ bezeichnet ein Veröffentlichungsjahr bei unbekanntem Kompositionsjahr.');table.before(note);
 try{
 const response=await fetch(base+'/app/site-data'+(de?'-de':'')+'.json');if(!response.ok)throw Error('Catalogue unavailable');const data=await response.json();
 const text=html=>{const e=document.createElement('div');e.innerHTML=html||'';return e.textContent;};
 function years(value){const match=String(value||'').match(/\b(1[89]\d{2})(?:\s*[-–/]\s*(\d{2,4}))?/);if(!match)return[];const start=+match[1],end=match[2]?(match[2].length===2?Math.floor(start/100)*100+ +match[2]:+match[2]):start;return Array.from({length:Math.min(100,Math.max(0,end-start))+1},(_,i)=>start+i);}
 const works=data.catalogue.map(r=>{let dates=years(r.year_of_composition),pub=false;if(!dates.length){const match=text((r.further_details||'')+' '+(r.availability||'')).match(/(?:published|publiziert|erschienen|veröffentlicht)\s*:?\s*(1[89]\d{2})/i);if(match){dates=[+match[1]];pub=true;}else{dates=years(text(r.publisher));pub=dates.length>0;}}return{r,dates,pub};});
 function panel(dates){const div=document.createElement('div');div.className='chronology-works';const matched=works.filter(w=>w.dates.some(y=>dates.includes(y)));const h=document.createElement('h3');h.textContent=t('Music from ','Musik aus ')+dates[0]+(dates.length>1?'–'+dates.at(-1):'');div.append(h);if(!matched.length){const p=document.createElement('p');p.textContent=t('No dated works in the catalogue for this period.','Für diesen Zeitraum sind keine datierten Werke verzeichnet.');div.append(p);return div;}const ul=document.createElement('ul');matched.forEach(({r,pub,dates:dy})=>{const li=document.createElement('li'),a=document.createElement('a');a.href=base+(de?'/de':'')+'/works/show/'+r.id+'/';a.textContent=text(r.title)+(r.opus_no?' · Op. '+r.opus_no:'');li.append(a,document.createTextNode(pub?' (pub. '+dy[0]+')':''));ul.append(li);});div.append(ul);return div;}
 table.querySelectorAll('tr').forEach((row,i)=>{const cell=row.cells[0];if(!cell)return;const dates=years(cell.textContent);if(!dates.length)return;const button=document.createElement('button');button.type='button';button.className='chronology-year';button.innerHTML=cell.innerHTML;cell.replaceChildren(button);const box=panel(dates);box.id='chronology-period-'+i;box.hidden=true;button.setAttribute('aria-controls',box.id);button.setAttribute('aria-expanded','false');row.cells[row.cells.length-1].append(box);let pinned=false;const show=open=>{box.hidden=!open;button.setAttribute('aria-expanded',String(open));};row.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse')show(true);});row.addEventListener('pointerleave',()=>{if(!pinned&&!row.contains(document.activeElement))show(false);});button.addEventListener('click',()=>{pinned=!pinned;show(pinned);});row.addEventListener('keydown',e=>{if(e.key==='Escape'){pinned=false;show(false);button.focus();}});});
 const explorer=document.createElement('section');explorer.className='chronology-explorer';const label=document.createElement('label');label.htmlFor='chronology-browse';label.textContent=t('Explore every year represented in the works catalogue','Alle im Werkverzeichnis vertretenen Jahre entdecken');const select=document.createElement('select');select.id=label.htmlFor;const placeholder=new Option(t('Choose a year','Jahr auswählen'),'');select.append(placeholder);[...new Set(works.flatMap(w=>w.dates))].sort().forEach(y=>select.append(new Option(String(y),String(y))));const target=document.createElement('div');target.setAttribute('aria-live','polite');select.addEventListener('change',()=>target.replaceChildren(...(select.value?[panel([+select.value])]:[])));explorer.append(label,select,target);table.before(explorer);
 }catch(error){note.textContent=t('The works could not be loaded. Please reload the page to explore the chronology.','Die Werke konnten nicht geladen werden. Bitte laden Sie die Seite erneut.');console.error(error);}
})();
